### ISSUE TITLE
./data/info.csv file

### ISSUE THREAD

**Issue by Jakub-Svoboda** [harish-2306/Facenet-TF#1]
When I try running the train.py as described in the readme, I get an error because the info.csv file is missing. What exactly is this file supposed to contain? Some info about the dataset? In what format? Is this related to the dataset? Also which dataset did you use?

**Comment by harxish** [comment]
Hey thanks for using the repo. The error is because I haven't uploaded the train directory. It's actually a directory of TF records and an CSV file which specifies the directories contents. You could just edit the data loading part to your own convience. 

Do say me if you find any more difficulties :)

**Comment by harxish** [comment]
> When I try running the train.py as described in the readme, I get an error because the info.csv file is missing. What exactly is this file supposed to contain? Some info about the dataset? In what format? Is this related to the dataset? Also which dataset did you use?

Hey thanks for using the repo. The error is because I haven't uploaded the train directory. It's actually a directory of TF records and an CSV file which specifies the directories contents. You could just edit the data loading part to your own convience. 

Do say me if you find any more difficulties :)

**Comment by harxish** [comment]
Hey, thanks for using the repo. Actually the file you are missing is in my dataset directory. My dataset dir contains tfrcds and an info.csv file. I haven't uploaded it. You could change that part alone by replacing it for your convenience to suit your dataset (in the src/train.py file).

Do say me if you find any more difficulties.

**Comment by lablabla** [comment]
Hi
Thanks to the work
can you please share how the data is suppose to be structured?
the images, the labels?

what is in the info.csv file, and what dataset did you test on?
thanks again

**Comment by harxish** [comment]
Hey sorry for the delayed response. The code is fixed now and can work on normal images with the directory holding the class label.
I have used VggFace2 for this model :))
